LearnerPlatform/LearnerPlatform/Controllers/ShowPathsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Learning_strategy;
using LearnerPlatform.Models.Snap97_NS_CS;

namespace LearnerPlatform.Controllers
{
    public class ShowPathsController : Controller
    {
        // GET: ShowPaths
        //@Html.ActionLink("Show Courses", "GetPathDetails", new { id=item.path_id})
        public ActionResult Index()
        {
            if (Session["id"] == null)
            {
                Session["timeout"] = "Session Expired.....";
                return RedirectToAction("Index", "Login");
            }

            else
            {
                Learning_strategy_class obj = new Learning_strategy_class();
                obj.delete_Null_Path();
                List<Snap97_NS_CS.Learning_path_masted> master_path = obj.Get_learning_path((int)Session["id"]);
                List<Learning_path_masted> local_master_path = new List<Learning_path_masted>();
                foreach (var element in master_path)
                {
                    local_master_path.Add(new Learning_path_masted()
                    {
                        learner_id = element.learner_id,
                        path_id = element.path_id,
                        pathname = element.pathName,
                        creation_date = element.creation_date
                    });
                }
                return View(local_master_path);
            }
        }
        public ActionResult GetPathDetails(int id, string sortOrder)
        {
            if (Session["id"] == null)
            {
                Session["timeout"] = "Session Expired.....";
                return RedirectToAction("Index", "Login");
            }

            else
            {
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "course_dec" : "";
                ViewBag.DurationSortParm = sortOrder == "Duration" ? "Duration_desc" : "Duration";
                List<Course> courses = new List<Course>();
                Learning_strategy_class obj = new Learning_strategy_class();
                List<int> courseIDs = obj.Get_course_by_path(id);
                List<Snap97_NS_CS.Course> AllCourses = obj.GetCourses();
                foreach (int courseid in courseIDs)
                {
                    Snap97_NS_CS.Course c = AllCourses.Where(x => x.course_id == courseid).FirstOrDefault();
                    courses.Add(
                        new Course()
                        {
                            course_id = c.course_id,
                            course_duration = c.course_duration,
                            course_description = c.course_description,
                            course_lvl = (course_levels)c.course_lvl,
                            course_name = c.course_name,
                        //CourseStatus = course_status.enrolled
                    }
                        );
                }
                switch (sortOrder)
                {
                    case "course_dec":
                        courses = courses.OrderByDescending(s => s.course_name).ToList();
                        break;
                    case "Duration":
                        courses = courses.OrderBy(s => s.course_duration).ToList();
                        break;
                    case "Duration_desc":
                        courses = courses.OrderByDescending(s => s.course_duration).ToList();
                        break;
                    default:
                        courses = courses.OrderBy(s => s.course_name).ToList();
                        break;
                }
                return View(courses);
            }
        }
    }
}

LearnerPlatform/LearnerPlatform/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title _Learners Platforn</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Login","Index","Login", new { area = "" },new {@class="navbar-brand" })
            </div>
            <div>
                @Html.ActionLink("Register","Index","Register", new { area = "" },new {@class="navbar-brand" })
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        
        <footer style="position:fixed; bottom:20px;">
            <hr />
            <p >&copy; @DateTime.Now.Year _Learners Platforn</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

LearnerPlatform/LearnerPlatform/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title _Learners Platforn</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })|
                @Html.ActionLink("Course", "Index", "Course", new { area = "" }, new { @class = "navbar-brand" })|
                @Html.ActionLink("My Learning Paths", "Index", "ShowPaths", new { area = "" }, new { @class = "navbar-brand" })|
                @Html.ActionLink("Logout", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        
        <footer style ="position:inherit; bottom:20px;">
            <hr />
            <p>&copy; @DateTime.Now.Year _Learners Platforn</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>