LearnerPlatform/LearnerPlatform/Controllers/LearningPathController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LearnerPlatform.Models;
using LearnerPlatform.Models.Snap97_NS_CS;
using Learning_strategy;
using PagedList;


namespace LearnerPlatform.Controllers
{
    public class LearningPathController : Controller
    {
        // GET: LearningPath
        static List<Course> c = new List<Course>();
        public ActionResult Index(string searchTerm, string currentFilter, string sortOrder, int? page)
        {
            ViewData["Message"] = Session["Add_Message"];
            Learning_strategy_class obj = new Learning_strategy_class();
            obj.delete_Null_Path();
            if (Session["id"] == null)
            {
                Session["timeout"] = "Session Expired.....";
                return RedirectToAction("Index", "Login");
            }

            else
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                if (searchTerm != null)
                {
                    page = 1;
                }
                else
                {
                    searchTerm = currentFilter;
                }
                ViewBag.CurrentFilter = searchTerm;
                int i = obj.Get_new_pathid((int)Session["id"]);
                if (i.Equals(0))
                {
                    obj.Create_learning_path((int)Session["id"]);
                    i = obj.Get_new_pathid((int)Session["id"]);
                }
                Session["PathId"] = i;
                IEnumerable<Snap97_NS_CS.Course> courseobj = 
                    obj.GetCourses().Where(x => searchTerm == null ||
                    x.course_name.ToUpper().Contains(searchTerm.ToUpper())||
                    x.course_description.ToUpper().Contains(searchTerm.ToUpper()));
                List<Course> c = new List<Course>();
                foreach (var course in courseobj)
                {
                    c.Add(
                            new Course()
                            {
                                course_id =course.course_id,
                                course_name=course.course_name,
                                course_description=course.course_description,
                                course_duration=course.course_duration,
                                course_lvl=(course_levels)course.course_lvl
                    }) ;
                }

                switch (sortOrder)
                {
                    case "name_desc":
                        c = c.OrderByDescending(s => s.course_name).ToList();
                        break;
                    default:
                        c = c.OrderBy(s => s.course_name).ToList();
                        break;
                }
                int pageSize = 5;
                int pageNumber = (page ?? 1);
                return View(c.ToPagedList(pageNumber, pageSize));
            }
        }
        public ActionResult AddToPath(int id)
        {
            if (Session["id"] == null)
            {
                Session["timeout"] = "Session Expired.....";
                return RedirectToAction("Index", "Login");
            }

            else
            {
                if (id == 0)
                {
                    return View(c);
                }
                else
                {
                    Session["Add_Message"] = " ";
                    Learning_strategy_class obj = new Learning_strategy_class();
                    Snap97_NS_CS.Course courseobj = obj.GetCourses().Where(x => x.course_id == id).FirstOrDefault();
                    Course course = new Course()
                    {
                        course_description = courseobj.course_description,
                        course_duration = courseobj.course_duration,
                        course_id = courseobj.course_id,
                        course_lvl = (course_levels)courseobj.course_lvl,
                        course_name = courseobj.course_name
                    };
                    foreach (var c1 in c)
                    {
                        if (c1.course_id == courseobj.course_id)
                        {
                            Session["Add_Message"] = "Course Already Present in the Path";
                            return RedirectToAction("index");
                        }
                    }
                    c.Add(course);
                    return View(c);
                }
            }
        }
        public ActionResult delete(int id)
        {
            if (Session["id"] == null)
            {
                Session["timeout"] = "Session Expired.....";
                return RedirectToAction("Index", "Login");
            }

            else
            {
                Learning_strategy_class obj = new Learning_strategy_class();
                Snap97_NS_CS.Course course = obj.GetCourses().Where(x => x.course_id == id).FirstOrDefault();
                Course c = new Course();
                c.course_id = course.course_id;
                c.course_name = course.course_name;
                c.course_description = course.course_description;
                c.course_duration = course.course_duration;
                c.course_lvl = (course_levels)course.course_lvl;
                return View(c);
            }
        }
        public ActionResult remove(int id)
        {
            if (Session["id"] == null)
            {
                Session["timeout"] = "Session Expired.....";
                return RedirectToAction("Index", "Login");
            }

            else
            {
                c.RemoveAll(x => x.course_id == id);
                return RedirectToAction("AddToPath", new { id = 0 });
            }
        }





        public ActionResult CreatePath()
        {
            if (Session["id"] == null)
            {
                Session["timeout"] = "Session Expired.....";
                return RedirectToAction("Index", "Login");
            }

            else
            {
                if (c.Count() != 0)
                {
                    return View(c);
                }
                else
                {
                    Session["Add_Message"] = "Add Course Before You Create Path";
                    return RedirectToAction("Index");
                }
            }
        }
        [HttpPost]
        public ActionResult CreatePath(string pathname)
        {
            if (Session["id"] == null)
            {
                Session["timeout"] = "Session Expired.....";
                return RedirectToAction("Index", "Login");
            }

            else
            {
                Learning_strategy_class obj = new Learning_strategy_class();
                obj.Name_my_path((int)Session["PathId"], pathname);
                foreach (var i in c)
                {
                    obj.Add_course_to_lp((int)Session["PathId"], i.course_id);

                }
                c.Clear();
                obj.delete_Null_Path();
                Session["PathId"] = null;
                return RedirectToAction("index", "course");
            }
        }
    }
}

LearnerPlatform/LearnerPlatform/Views/LearningPath/AddToPath.cshtml
@model IEnumerable<LearnerPlatform.Models.Snap97_NS_CS.Course>
<h2>AddToPath</h2>

<p>
    @Html.ActionLink("Add More", "Index")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.course_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.course_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.course_duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.course_description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.course_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.course_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.course_duration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.course_description)
        </td>
        <td>@Html.ActionLink("Remove From Path","delete",new {id=item.course_id})
        </td>
    </tr>
}
</table>
<<button type="button">@Html.ActionLink("Create Path","CreatePath")</button>

LearnerPlatform/LearnerPlatform/Views/LearningPath/CreatePath.cshtml
@model IEnumerable<LearnerPlatform.Models.Snap97_NS_CS.Course>

<p>
    <h1>Confirm the Courses</h1>
</p>
@using (Html.BeginForm("CreatePath", "LearningPath", FormMethod.Post))
{
    <label>Enter Name Of The Path</label>
    <input type="text" id="pathname" name="pathname" required/>
    <table class="table">
        <tr>
            <th>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.course_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.course_duration)
            </th>
            <th>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.HiddenFor(modelItem => item.course_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.course_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.course_duration)
                </td>
                <td>
                </td>
                <td>
                    @Html.ActionLink("Delete", "delete", new { id = item.course_id }) |
                </td>
            </tr>
        }

    </table>
    <input type="submit" value="Submit" />
}

LearnerPlatform/LearnerPlatform/Views/LearningPath/Index.cshtml
@model PagedList.IPagedList<LearnerPlatform.Models.Snap97_NS_CS.Course>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<br />
@using (Html.BeginForm("Index", "LearningPath", FormMethod.Get))
{
    <p>
        @Html.TextBox("searchTerm", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<br />
<h2 class="text-danger">
    @Html.ViewData["Message"]
</h2>
<table class="table">
    <tr>
        <th>

        </th>
        <th>
            @Html.ActionLink("Course", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
        </th>
        <th>
            @Html.DisplayName("Description")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.HiddenFor(modelItem => item.course_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.course_name)
            </td>
            <td>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.course_description)
            </td>
            <td>
                @Html.ActionLink("Add", "AddToPath", new { id = item.course_id })
        </tr>
    }
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

LearnerPlatform/LearnerPlatform/Views/LearningPath/delete.cshtml
@model LearnerPlatform.Models.Snap97_NS_CS.Course

@{
    ViewBag.Title = "delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Confirm Deletion</h2>

<div>
    <hr />
    <h4>Are You sure You want to delete</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.HiddenFor(model => model.course_id)
        </dt>

        <dd>
            @Html.HiddenFor(model => model.course_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.course_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.course_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.course_duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.course_duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.course_description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.course_description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Delete", "remove",new {id=Model.course_id })
</p>